### ISSUE TITLE
Workaround for lack of ability to write to files in App Engine

### ISSUE THREAD

**Issue by Ayaykos** [tl-its-umich-edu/m-voice#12]
https://cloud.google.com/appengine/docs/standard/php/googlestorage/ 
The method we are using to find updates in the meals/locations is a diff that compares files, which in our case requires the ability to write to them. 

App Engine doesn't normally allow this for deployed apps, so either we'll have to use Google's proposal of Storage Buckets or use a different system that doesn't compare files.

**Comment by jonespm** [comment]
Yeah, I thought about this when you were writing files, that it wouldn't be the same on App Engine. 

We could just dump the diff files into Datastore or Storage and then retrieve them

We could probably also just put them into Datastore (or maybe CloudSQL though I think it's just a simple key/value) and compare directly. 

This is the pseudocode right?

```
Retrieve Meals and Locations from the API 
Remove the Meals and Locations we ignore

If first run 
  save all the values (somewhere)
Else
  Compare new values to existing value
  In SQL this would be just like SELECT * FROM DATATABLE WHERE NOT IN [retrieved meals/locations]
  Figure out if it's an addition or a deletion, report out the differences (so we can manually update)
```

**Comment by Ayaykos** [comment]
Yep that's about right. I'm considering using Datastore to keep things more organized since we're already using it for the entities.

**Comment by Ayaykos** [comment]
I've been looking into automating interaction with Datalab which is what we used in the Coursera course to populate the Datastore entities with Python Notebooks, because if we do it through Datalab it's simpler and no authentication necessary.

**Comment by Ayaykos** [comment]
However I feel like this might be overkill so I'm going to try out this one method that doesn't deal with files at all before going that direction.
