### ISSUE TITLE
Update variable names and other items identified by pylint to pep8 

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/m-voice#29]
Since you're changing variable names, the python preferred style for variables is snake_case ([pep8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)) all lowercase separated by underscores.  StudlyCaps are used for class names.

Sticking with the language conventions will make developing in the future easier! 

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/m-voice/pull/28_

**Comment by jonespm** [comment]
Assigning to @Ayaykos to update the variables in this project. 

If you run pylint it will display all of the issues, most of which should be addressed.
pylint flask/main.py

`flask/main.py:27:0: C0103: Function name "isPartialTerm" doesn't conform to snake_case naming style (invalid-name)`

You should also be able to install pylint or some other linter in your IDE.

**Comment by jonespm** [comment]
The only pylint item I *usually* ignore is E401 (multiple imports on one line) and E501 (max line length) though I'll set a line length to 120.

**Comment by Ayaykos** [comment]
Do you want me to make functions snake_case too?

**Comment by jonespm** [comment]
According to pep8 function and variable names are the same format (snake case)

Can look at code in a large project like [Django](https://github.com/django/django/blob/master/django/http/request.py) to get an idea.

There are a few exceptions, special function names like `__init__ ` of course and user defined type variables, which we aren't using here either in either case but probably would be nice to do. 

I've gotten pretty comfortable with this style lately, even doing Java for so long.

Thanks!

**Comment by jonespm** [comment]
Resolved by #30
